language: cpp
dist: trusty
sudo: false
cache: ccache
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libboost-dev
    - libboost-system-dev
env:
  global:
  - ENV_EVAL="CXX=g++-7 CC=gcc-7"
  - MAKEFLAGS="-j 3"
  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebInfo
  - BUILD_TYPE=MinSizeRel
  - BUILD_TYPE=Release
before_install:
- eval "${ENV_EVAL}"
before_script:
- mkdir build
- cd build
script:
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
- make
- ctest
after_failure:
- cat Testing/Temporary/LastTest.log
